%================================================================
%        Prey-Predator Simulation Family Member Generator
%================================================================
%
% Name of File: Habitats.m
%
% Description: This is an auto-generated file generated by
%   PreyPredatorFamilyGenerator.exe AML compiler & composer.
%   
%   Contains algorithms to calculate factors required by the
%   simulation algorithm.
%
% Copyright:
%  This software is open source and reuseable by anyone within
%  the organization.
%================================================================
classdef Habitats
    %UNTITLED Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
    end
    
    methods (Static)
        function [WM, FM, AFM, EFM] = getValues(habitat)
            switch habitat
                case char('Forest')
                    WM =2;
                    FM=2;
                    %nothing in favor of agressivity.
                    AFM=1;
                    %trees and vegetation allow for
                    %camaflouge, hiding places, etc..
                    EFM=1.5;
                case char('Meadows')
                    %meadows have decent vegetation
                    %avg rainfall, average land. This is
                    %the default.
                    WM=1;
                    FM=1.5;
                    AFM=1;
                    EFM=1;
                case char('Desert')
                    WM =0.5;
                    FM=0.5;
                    %AFM is high, EFM lower (being highly active
                    %is not helpful because of low water supply)
                    AFM=2;
                    EFM=0.8;
                case char('Prairie')
                    %moderate rainfall, moderate vegetation (no trees)
                    %... this is what it means to be average.
                    WM=1;
                    FM=1;
                    AFM=1;
                    EFM=1;
                case char('Swamp')
                    %swamp is a forest with large water source.
                    %the water is stagnant (nonmoving), and can have 
                    %clean or dirty water sources.
                    %WM starts high, but WM isn't affected as much.
                    %vegetation is high and FM high.
                    %
                    WM=1.5;
                    FM=2;
                    AFM=1;
                    EFM=1;
                case char('Mountains')
                    %mountains have rain shadows
                    %or places where there is no water/vegetation,
                    %and where rainfall doesn't do much to those parts.
                    %therefore WM and FM are lower in mountains.
                    WM = 0.8;
                    FM=0.8;
                    %EFM is higher since mountainous allows
                    %for obstacle usage, caverns, nimble movements,
                    %agility, and other traits to allow for evasivity
                    AFM=1;
                    EFM=1.5;
                case char('Antarctic')
                    %VERY little rainfall in antarctic (6.5" per year)
                    %BUT there are natural sources of water (snow, ice
                    %glaciers). In fact, 70% of the world's freshwater
                    %is in the Antarctic. Therefore, w is HUGE,
                    %although the increase is small.
                    WM = 0.1;
                    %1% of the land is available for vegetation to 
                    %grow. SO FM is really low as well.
                    FM=0.01;
                    %because of the lack of water and food sources
                    %species are WAY more aggressive.
                    %because of the nature of the cold, dry habitat, the
                    %antarctic is similar to a desert.
                    AFM=2;
                    EFM=0.8;
                otherwise
                    WM = 1;
                    FM=1.5;
                    AFM=1;
                    EFM=1;
            
            end
        end
    end
    
end
%================================================================
%----------------------------------------------------------------
% 2015-11-29:
%  Auto-generated file.
%----------------------------------------------------------------
%================================================================
